services:
  - type: web
    name: reddit-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_server:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: REDDIT_USERNAME
        sync: false
      - key: REDDIT_PASSWORD
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: USER_AGENT
        sync: false 